### PR TITLE
Move .NET 8 preview images to Debian 12 Bookworm

### PR DESCRIPTION
**Pull request by lbussell**
Fixes https://github.com/dotnet/dotnet-docker/issues/4322

### CODE REVIEW

**Review by mthalman — APPROVED** [review]
Looks great! Glad to see the only updates needed were libicu and libssl versions.

**Review by MichaelSimons — COMMENTED** [review]
There appear to be some aspnet/8.0 Dockerfiles that were copied incorrectly.  The paths contain both bookworm and bullseye.

See https://github.com/dotnet/dotnet-docker/blob/27e052fe1e49a2aca3f0bbfd48e39f2630dc68f3/src/aspnet/8.0/bookworm-slim/bullseye-slim/amd64/Dockerfile

**Review by MichaelSimons — APPROVED** [review]

**Comment by mthalman** [comment]
Looks like pipeline triggers are having issues.

image

**Pull request merged**
