### PR TITLE
Introduce HostName to EnvironmentInfo.

### PR DESCRIPTION
**Pull request by jaliyaudagedara**
Introduce HostName to EnvironmentInfo.
Remove unused variable.

### CODE REVIEW

**Review by mthalman — COMMENTED** [review]
Seems a reasonable addition. In this case, I think equivalent changes should be made to the console-app based sample at https://github.com/dotnet/dotnet-docker/tree/main/samples/dotnetapp

**Comment by jaliyaudagedara** [comment]
@mthalman,

Didn't think it will be useful to have HostName in the console app. 

Updated.

**Comment by mthalman** [comment]
@richlander - Any input on these changes? Do you agree to have it in the console app as well or just the web app?

**Comment by jaliyaudagedara** [comment]
@richlander, appreciate if you can have a look at this, thanks!

**Review by richlander — APPROVED** [review]

**Pull request merged**
