### PR TITLE
Publish aspnetapp-non-root sample images

### PR DESCRIPTION
**Pull request by lbussell**
Fixes https://github.com/dotnet/dotnet-docker/issues/4520

### CODE REVIEW

**Comment by mthalman** [comment]
Build error: 

` ---> System.InvalidOperationException: A value was not found for the ARG '$BUILDPLATFORM' in 'samples/aspnetapp/Dockerfile.alpine-non-root'`

Oh no! Our lovely Dockerfile isn't incompatible with our own infrastructure.

@richlander - Do you mind if we remove the usage of `$BUILDPLATFORM` and `$TARGETARCH` from Dockerfile.alpine-non-root? This pattern isn't applied consistently to the Dockerfiles anyway. We'd need to make changes to Image Builder in order to support the use of variable references in the `FROM` instruction.

**Comment by richlander** [comment]
That's unfortunate. I referenced that Dockerfile in this post: https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/. Should I make a new one that is multi-arch specific and then update the link?

**Comment by mthalman** [comment]
The build error may be caused by the lack of `customBuildLegGroups` for the new entries in the manifest. I didn't think it was needed, but it might be the reason that the matrix generation is getting screwed up. I would try adding `customBuildLegGroups` to those entries, copying from the other ones, to see if that fixes things.

**Comment by mthalman** [comment]
The change to the matrix type should not be necessary, nor it is desired. Did my [suggestion](https://github.com/dotnet/dotnet-docker/pull/4542#issuecomment-1498183722) above not work in your testing?

**Comment by mthalman** [comment]
Build error says `failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument`

I think this is because BuildKit is not enabled by default on the build agents. I _think_ we can workaround this by adding the following to the top of the sample Dockerfile:

```Dockerfile
# syntax=docker/dockerfile:1
```

**Comment by richlander** [comment]
That would be unfortunate to have to add. These images are intended to be best practice and that directive doesn't seem otherwise needed. Certainly, if we need that as a temporary measure, that's fine.

**Comment by lbussell** [comment]
> That would be unfortunate to have to add. These images are intended to be best practice and that directive doesn't seem otherwise needed. Certainly, if we need that as a temporary measure, that's fine.

That's alright, it still doesn't work even with the directive.

**Comment by mthalman** [comment]
I think this will require a change to Image Builder then to explicitly ensure BuildKit is enabled so that it executes commands like this: `DOCKER_BUILDKIT=1 docker build ...`

**Comment by mthalman** [comment]
Still getting the [same error](https://github.com/dotnet/dotnet-docker/pull/4542#issuecomment-1499428268). I don't think the buildkit changes have flowed in yet. https://github.com/dotnet/docker-tools/pull/1129 is still open.

**Comment by lbussell** [comment]
New ImageBuilder should come in with https://github.com/dotnet/dotnet-docker/pull/4598.

**Comment by mthalman** [comment]
This is blocked after the need to revert the build kit change in https://github.com/dotnet/docker-tools/pull/1134. That's required in order to finish this work. Since that work is planned for any time soon, we'll just close this for now.

**Pull request closed without merging**
