### PR TITLE
Updates for 2.1/3.1 servicing

### PR DESCRIPTION
**Pull request by mthalman**
Related to #2076

### CODE REVIEW

**Comment by MichaelSimons** [comment]
Is there a reason why not all the changes in nightly haven't been included?  

https://github.com/dotnet/dotnet-docker/commit/a307fb125e1f1b35ad0ddf39858c569e0b75175b
https://github.com/dotnet/dotnet-docker/commit/40bbb6853e4bbf6e531f875ae2b6ea75fea18e30

**Comment by mthalman** [comment]
> Is there a reason why not all the changes in nightly haven't been included?
> 
> [a307fb1](https://github.com/dotnet/dotnet-docker/commit/a307fb125e1f1b35ad0ddf39858c569e0b75175b)
> [40bbb68](https://github.com/dotnet/dotnet-docker/commit/40bbb6853e4bbf6e531f875ae2b6ea75fea18e30)

I missed the image size baseline one.  And for some reason, I was thinking we weren't ready to merge the manifest.versions.json changes over but I guess there's no reason why we shouldn't.

**Comment by mthalman** [comment]
Or wait, the image size baseline changes were merged.  It's in the list of commits.

**Comment by MichaelSimons** [comment]
I think the versions change should be merged.  Basically the master and nightly branches should be the same in regards to infrastructure after the monthly servicing releases.

**Pull request merged**
