### PR TITLE
.NET Container Images Servicing August 2023

### PR DESCRIPTION
**Pull request by lbussell**

### CODE REVIEW

**Review by mthalman — APPROVED** [review]

**Comment by lbussell** [comment]
@mthalman, how should we coordinate the timing of this PR with https://github.com/dotnet/dotnet-docker/pull/4790 (ImageBuilder with BuildKit changes)? Merge it now or include it in this PR?

**Comment by mthalman** [comment]
Does https://github.com/dotnet/dotnet-docker/pull/4790 require any changes that are in this PR? If not, then I would say it can be merged right now.

**Comment by lbussell** [comment]
> Does #4790 require any changes that are in this PR?

No, all of the changes are in ImageBuilder. I will merge it now then.

**Comment by jander-msft** [comment]
.NET Monitor LGTM

**Review by jander-msft — APPROVED** [review]

**Pull request merged**
