### PR TITLE
Updating Nano Server Dockerfiles to be based on 10.0.14393.1198 

### PR DESCRIPTION
**Pull request by v-hongbl**

### CODE REVIEW

**Comment by rakeshsinghranchi** [comment]
LGTM

**Comment by natemcmaster** [comment]
Are you planning to make a PR to update https://github.com/aspnet/aspnet-docker as well?

**Comment by v-hongbl** [comment]
No, I'm not changing aspnet-docker image. Someone else may make the change.

**Comment by rakeshsinghranchi** [comment]
@MichaelSimons  Michael owns aspnet-docker image as of now.

**Comment by natemcmaster** [comment]
Ok, just trying to avoid duplicate effort. I'll update the aspnet-docker images to the latest nanoserver once this update finishes building on CI.

**Pull request merged**
