### PR TITLE
Update PowerShell Preview to 7.1.0-rc.1

### PR DESCRIPTION
**Pull request by rjmholt**

### CODE REVIEW

**Comment by MichaelSimons** [comment]
This PR should be made in the `nightly` branch not `master`.  See the [CONTRIBUTING guide](https://github.com/dotnet/dotnet-docker/blob/master/CONTRIBUTING.md#branches).  Any changes affecting the components included in images cannot be made without a tag change.

**Comment by rjmholt** [comment]
> This PR should be made in the nightly branch not master

Ah yep, changed.

**Comment by MichaelSimons** [comment]
@rjmholt - Thanks for targeting `nightly`.  Can you sync to the latest?  There was a new 5.0 sdk Dockerfile recently added that isn't included in the changes - https://github.com/dotnet/dotnet-docker/pull/2274.

**Comment by rjmholt** [comment]
I've rebased and rerun the generation command, but no new changes were created. Will try to start over

**Comment by MichaelSimons** [comment]
@rjmholt, I'm sorry I must have overlooked your changes - I see the new Dockerfile now - https://github.com/dotnet/dotnet-docker/pull/2283/files#diff-c6f0c39c5efd0809c61f13cf13affbf1

**Review by MichaelSimons — APPROVED** [review]

**Review by mthalman — APPROVED** [review]

**Pull request merged**
