### PR TITLE
Create updaters for each product independently.

### PR DESCRIPTION
**Pull request by jander-msft**
While dotnet-monitor does share the same version with the runtime/aspnet/sdk, that will not always be the case. With these changes, I've refactored the update-dependencies tool to update each product independently so that each product may be versioned independent of the other products.

### CODE REVIEW

**Comment by mthalman** [comment]
What is functionally incorrect with how things work right now?  The tool can already handle the products being independently versioned so it's not clear to me what this is changing.

**Comment by jander-msft** [comment]
> What is functionally incorrect with how things work right now? The tool can already handle the products being independently versioned so it's not clear to me what this is changing.

If you look at what was formerly UpdateFiles:
```
            // NOTE: dotnet-monitor will diverge its versioning in the future; this will need to be refactored in	            List<IDependencyInfo> buildInfos = new List<IDependencyInfo>();
            // some way to allow updaters to be collected for each product's individual version.	            List<IDependencyUpdater> updaters = new List<IDependencyUpdater>();
            string buildVersion = buildInfos.GetBuildVersion(RuntimeBuildInfoName) ??	
                buildInfos.GetBuildVersion(SdkBuildInfoName) ??	
                buildInfos.GetBuildVersion(AspNetCoreBuildInfoName) ??	
                buildInfos.GetBuildVersion(MonitorBuildInfoName);	
            string productVersion = buildVersion.Split('-')[0];	
            string dockerfileVersion = productVersion.Substring(0, productVersion.LastIndexOf('.'));	
            IEnumerable<IDependencyUpdater> updaters = GetUpdaters(dockerfileVersion, buildInfos);
```

It would only take the version of the first product that it could find (runtime, then sdk, then aspnetcore, then dotnet-monitor), create the Dockerfile version, and only search for Dockerfiles that had that version. So when .NET Core goes to 6.0 or if dotnet-monitor moves to 5.1.X, then dotnet-montior would not get updated anymore if any of runtime, sdk, or aspnetcore versions were specified.

**Comment by jander-msft** [comment]
> > What is functionally incorrect with how things work right now? The tool can already handle the products being independently versioned so it's not clear to me what this is changing.
> 
> If you look at what was formerly UpdateFiles:
> 
> ```
>             // NOTE: dotnet-monitor will diverge its versioning in the future; this will need to be refactored in
>             // some way to allow updaters to be collected for each product's individual version.
>             string buildVersion = buildInfos.GetBuildVersion(RuntimeBuildInfoName) ??	
>                 buildInfos.GetBuildVersion(SdkBuildInfoName) ??	
>                 buildInfos.GetBuildVersion(AspNetCoreBuildInfoName) ??	
>                 buildInfos.GetBuildVersion(MonitorBuildInfoName);	
>             string productVersion = buildVersion.Split('-')[0];	
>             string dockerfileVersion = productVersion.Substring(0, productVersion.LastIndexOf('.'));	
>             IEnumerable<IDependencyUpdater> updaters = GetUpdaters(dockerfileVersion, buildInfos);
> ```
> 
> It would only take the version of the first product that it could find (runtime, then sdk, then aspnetcore, then dotnet-monitor), create the Dockerfile version, and only search for Dockerfiles that had that version. So when .NET Core goes to 6.0 or if dotnet-monitor moves to 5.1.X, then dotnet-montior would not get updated anymore if any of runtime, sdk, or aspnetcore versions were specified.

Technically, we could run the update-dependencies tool for each product independently so that only one product is updated for each run of the tool, but that seemed like that was not the intended use based on how the pipeline already invokes the tool with all version information passed at once.

**Comment by MichaelSimons** [comment]
We have had several issues in the past in aspnet/sdk/runtime that blocked uptake of the latest builds until product changes were made.  In these type of situations, those issues shouldn't block uptake of the latest monitor/diagnostics versions.  If we onboard more image variants that are disparate, the pattern of a single PR to update all may not scale well in the aforementioned scenario.  I therefore lean towards having separate PRs.

**Comment by jander-msft** [comment]
> We have had several issues in the past in aspnet/sdk/runtime that blocked uptake of the latest builds until product changes were made. In these type of situations, those issues shouldn't block uptake of the latest monitor/diagnostics versions. If we onboard more image variants that are disparate, the pattern of a single PR to update all may not scale well in the aforementioned scenario. I therefore lean towards having separate PRs.

I've created a separate PR (#2027) that should run the update-dependencies tool just for dotnet-monitor so that it creates a separate update PR. If this is more of what you had in mind, I'll close out the refactoring PR.

**Comment by MichaelSimons** [comment]
I like your new proposal in #2027.

**Pull request closed without merging**
