### PR TITLE
Remove quotation marks from ASPNETCORE_URLS variable

### PR DESCRIPTION
**Pull request by adamradocz**
If https://+;http:// passed within quotation marks to ASPNETCORE_URLS variable, .net gives the following error:

```
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: Unrecognized scheme in server address '"https://+:443'. Only 'http://' is supported.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

Unhandled Exception: System.InvalidOperationException: Unrecognized scheme in server address '"https://+:443'. Only 'http://' is supported.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```

### CODE REVIEW

**Comment by mthalman** [comment]
I've tried the original command (with the quotes) on both my Windows and Mac machines and they both work correctly.  I'm not seeing this error.  If I use your suggested change to not have the quotes, it works fine with my Windows machine.  But it does not work on my Mac (I get can error saying `-bash: http://+: No such file or directory`).  

Can you provide more info on your environment?  What OS are you running?  What version of .NET (`dotnet --version`)?

**Comment by adamradocz** [comment]
I use Docker Compose, maybe that's the issue?

OS: Ubuntu 19.04 (GNU/Linux 5.0.0-16-generic x86_64)
Docker: 18.06.1-ce
Docker Compose: 1.21.0
.NET: .NET Core 3.0 preview 5

**Comment by mthalman** [comment]
So do you get this error when running it from the command line as indicated in the documentation?

**Comment by adamradocz** [comment]
Yes, I get this error when running from the command line or with docker-compose. Now I tested both ways and get the error with eighter method.

**Comment by mthalman** [comment]
Could you provide a full set of repro steps that I can execute from scratch?  I've created an ASP.NET app based on the 3.0-alpine image and I'm still not able to repro.  I've tried this on a Windows machine.  Are you only able to repro this on Ubuntu or can you also get it to occur in Windows or Mac?

**Comment by adamradocz** [comment]
This is the command I run: `docker run -it -e ASPNETCORE_URLS="https://+:443;http://+:80" --rm adamradocz/boinc-manager-web`

Here is the Dockerfile: https://github.com/adamradocz/boinc-manager/blob/master/Dockerfile.alpine

**Comment by mthalman** [comment]
I'm really stumped why you're seeing this.  I've now tried it on every OS and they all work fine.

Here's what I've done on an Ubuntu 19.04 VM:
1. `git clone https://github.com/adamradocz/boinc-manager.git`
2. `cd boinc-manager`
3. `sudo docker build -t boinc -f Dockerfile.alpine .`
4. `dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p <password>`
5. `sudo docker run --rm -it -p 8000:80 -p 8001:443 -e ASPNETCORE_URLS="https://+:443;http://+:80" -e ASPNETCORE_HTTPS_PORT=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="<password>" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v ${HOME}/.aspnet/https:/https/ boinc`

Output:
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://[::]:443
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
```

Can you try these exact steps yourself and let me know the results?  Otherwise, can you provide a new set of steps starting from step 3 that produces the error you're seeing?

**Comment by adamradocz** [comment]
Thank you for taking the time to test it. In a VM with a new Ubuntu it's working fine to me to with quotation marks. Strange.

**Pull request closed without merging**
