### PR TITLE
Update PowerShell to version 6.2.1

### PR DESCRIPTION
**Pull request by adityapatwardhan**
Update the version of PowerShell to the latest patch.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
Thanks for the PR @adityapatwardhan.  Can you merge in the latest changes from nightly?  `nanoserver-1903` images were added today and will need to be updated as well.

These change will get released with Preview 6.

**Comment by adityapatwardhan** [comment]
@MichaelSimons I have updated the PR to include nanoserver-1903. Please have another look.

**Comment by adityapatwardhan** [comment]
@MichaelSimons For some reason, it seems the CI is not kicking off.

**Comment by MichaelSimons** [comment]
@adityapatwardhan - there are reports of some issues with AZP.  We may need to queue manually.

As a friendly reminder, please sign the CLA.  You should only have to do it once.

**Comment by MichaelSimons** [comment]
@adityapatwardhan - there are reports of some issues with AZP.  We may need to queue manually.

As a friendly reminder, please sign the CLA.  You should only have to do it once.

**Comment by MichaelSimons** [comment]
The two CI failures are unrelated to these changes.  Proceeding with merge.

**Pull request merged**
