### PR TITLE
Revert "Add Environment API"

### PR DESCRIPTION
**Pull request by Andresmo01**
https://github.com/Andresmo01/dotnet-docker/tree/Andresmo01-patch-1

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/dotnet-docker?pullRequest=3712) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotnet-docker?pullRequest=3712) before we can accept your contribution.<br/><br/>:x: Andresmo01 [sign now](https://cla.dotnetfoundation.org/dotnet/dotnet-docker?pullRequest=3712)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotnet-docker?pullRequest=3712) it.</sub>

**Review by Andresmo01 — COMMENTED** [review]
https://github.com/Andresmo01/dotnet-docker/tree/Andresm1

**Comment by Andresmo01** [comment]
> [CLA assistant check](https://cla.dotnetfoundation.org/dotnet/dotnet-docker?pullRequest=3712) Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](JOSE ) before we can accept your contributiO QUE LICENCIA
on.x Andresmo01 [sign now](https://cla.dANDRES MIRANDA ES EL UNICotnetfoundation.org/dotnet/dotnet-docker?pullRequest=3712)You have signed the CLA already but the status is still pending? Let us [recheck]() it.

**Comment by mthalman** [comment]
This PR looks to have been mistakenly submitted. I'm closing it. 

@Andresmo01 - It looks like you're new to GitHub. Be sure to try things out in your own repo or forks before submitting to public repos. Thanks.

**Comment by Andresmo01** [comment]
[/Andresmo01-]( @azure-claudiu )

**Pull request closed without merging**
