### PR TITLE
Add Dockerfiles for CBL-Mariner (#2841)

### PR DESCRIPTION
**Pull request by mthalman**
Merges the 3.1 and 5.0 Dockerfiles for [CBL-Mariner](https://github.com/microsoft/CBL-Mariner) to main.  6.0 can't be merged yet; it will have to wait until Preview 5 ships due to RPM package availability.

Related to https://github.com/dotnet/dotnet-docker/issues/2837

### CODE REVIEW

**Comment by MichaelSimons** [comment]
I wasn't expecting to see the 6.0 Dockerfiles and templates included with this PR.  It puts the repo in a rather inconsistent state.  For example the manifest.versions entries aren't included which the templates reference.  Is it too much work to remove them?

**Comment by mthalman** [comment]
Ugh, me neither. My intent was to not include them. The Fork client I was using was being temperamental. I'll try to fix it up.

**Review by MichaelSimons — APPROVED** [review]
LGTM

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/issues/6379

**Pull request merged**
