### PR TITLE
Update 5.0 SDK to 5.0.300

### PR DESCRIPTION
**Pull request by mthalman**
Related to https://github.com/dotnet/dotnet-docker/issues/2830

### CODE REVIEW

**Review by MichaelSimons — APPROVED** [review]

**Comment by Youssef1313** [comment]
@mthalman Hi there!

This unfortunately out of sudden broke me since I had a `global.json` with 5.0.200.
Anyway to pin the version to exactly 5.0.200? Thanks in advance.

**Comment by mthalman** [comment]
> This unfortunately out of sudden broke me since I had a `global.json` with 5.0.200.
> Anyway to pin the version to exactly 5.0.200? Thanks in advance.

Yes, use the `5.0.203` tag, which was the previous version.  You can see the list of current tags at https://hub.docker.com/_/microsoft-dotnet-sdk.  By replacing any of the `5.0.300` tags with `5.0.203`, it'll give you the appropriate previous version.

**Comment by Youssef1313** [comment]
@mthalman Thanks for the very fast response!

**Pull request merged**
