### PR TITLE
Add Dockerfiles for Alpine 3.17

### PR DESCRIPTION
**Pull request by mthalman**
This adds new Dockerfiles that target Alpine 3.17, which currently has an RC release.

Moves the `x.0-alpine` tags from Alpine 3.16 to 3.17. Also removes Alpine 3.16 Dockerfiles for .NET 8.

### CODE REVIEW

**Review by MichaelSimons — APPROVED** [review]
LGTM, Any idea if 3.17 will be released prior to Dec servicing?  If it will release after Dec servicing will you defer merging this PR until after Dec servicing?

**Comment by mthalman** [comment]
> LGTM, Any idea if 3.17 will be released prior to Dec servicing? If it will release after Dec servicing will you defer merging this PR until after Dec servicing?

Can you explain why Dec servicing impacts this? I don't understand why it shouldn't be merged regardless of the timing.

**Comment by MichaelSimons** [comment]
> Can you explain why Dec servicing impacts this? 

Would it make it easier to merge changes from nightly to main for the release?

**Comment by mthalman** [comment]
> > Can you explain why Dec servicing impacts this?
> 
> Would it make it easier to merge changes from nightly to main for the release?

It shouldn't make a difference.

**Pull request merged**
