### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by FlowOverFail**
Update of the Dockerfile to fix a spelling error ('perfomance' -> 'performance').

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@FlowOverFail - thanks for pointing this out.  Would you mind replacing all occurrences of this misspelling?  This comment appears several places.

**Comment by FlowOverFail** [comment]
@MichaelSimons Sure thing.  I finally had time to catch up with some of the changes from .NET Core 2.0 to .NET Core 2.1, so I have been looking through the documentation and dockerfiles.  Cheers!

**Comment by MichaelSimons** [comment]
@FlowOverFail - thanks, I see 21 occurrences in the master branch that should be fixed.

**Comment by FlowOverFail** [comment]
@MichaelSimons My apologies, I forget to check through the entire branch.  I wrote a simple script to replace all occurrences.  I had a typo in my commit message, so I went back and fixed that.  Everything should be good now.

**Comment by FlowOverFail** [comment]
@MichaelSimons My apologies about all the commits, I kept misspelling occurrences for some reason.  I wrote a script to replace all occurrences.  Everything should be good now.

**Comment by MichaelSimons** [comment]
@FlowOverFail - Thanks for fixing this everywhere.

**Pull request merged**
