### PR TITLE
Update PowerShell for 3.1, 5.0 and 6.0 SDK images

### PR DESCRIPTION
**Pull request by adityapatwardhan**
Update all the corresponding dokerfiles for 3.1, 5.0 and 6.0 SDK images

### CODE REVIEW

**Comment by mthalman** [comment]
@adityapatwardhan - Can you revert the changes that were made in https://github.com/dotnet/dotnet-docker/pull/2489?  Please include that in this PR so that the tests can validate things.

**Comment by adityapatwardhan** [comment]
@mthalman Done.

**Comment by mthalman** [comment]
@adityapatwardhan - Sorry for the churn on this.  The tests are failing due to no Alpine support on Arm for PowerShell.  So the test changes you made need to be refined to only skip the tests for this skip condition rather than for all of 6.0.  See https://github.com/dotnet/dotnet-docker/issues/2544 for example code.

**Comment by adityapatwardhan** [comment]
Updated

**Pull request merged**
