### PR TITLE
Update readme for 1.1.0-preview1 runtime and 1.0.0-preview2.1 sdk release

### PR DESCRIPTION
**Pull request by MichaelSimons**
cc @richlander @naamunds

### CODE REVIEW

**Comment by MichaelSimons** [comment]
test NanoServer please

**Comment by MichaelSimons** [comment]
test NanoServer please

**Comment by MichaelSimons** [comment]
@naamunds  - I updated this section.  I also added this comment to the proposed new readme - https://github.com/dotnet/dotnet-docker/pull/135#discussion_r84955124

**Comment by naamunds** [comment]
@MichaelSimons Looks good.  I agree that we could remove that section altogether.

**Pull request merged**
