### PR TITLE
(Replaced by #680) Consistent environment variable names for DOTNET_RUNNING_IN_CONTAINER

### PR DESCRIPTION
**Pull request by fbeltrao**
This PR is a potential fix for issue #677 

I am however, not sure about the side effects of this change. It will potentially break any existing application that expects the old behavior. We could provide both for backward compatibility giving time for people to make code changes.

Another option is to fix this problem only in newer versions.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@fbeltrao - Thanks for making this PR.  As I noted in the #677 - I'm of the opinion that we should not make this a breaking change.  My preference would be to add the singular variable in the 2.1 images and then fix the problem going forward.  Lastly can you make this change in the `nightly` branch?  Nightly includes 2.2 and 3.0 images as well.  The changes will be available immediately in nightly and then get merged into master during the next patch Tuesday.

**Comment by fbeltrao** [comment]
@MichaelSimons thanks for the feedback. Just to make sure I understand your suggestions.

- To fix 2.2+ versions (currently in preview) we can make the breaking change, having only DOTNET_RUNNING_IN_CONTAINER for all images. This PR should be made on **nightly** branch.

- To fix 2.1 version (with LTSC) we cannot introduce a breaking change, therefore we should define both values (singular and plural) on windows images. The PR for this change should go to **$master** branch.

**Comment by MichaelSimons** [comment]
@fbeltrao - One small correction - both changes should go into `nightly`.  The 2.1 changes will get merged into `master` during the next .NET servicing event (e.g. patch Tuesday).

**Comment by fbeltrao** [comment]
@MichaelSimons new PR made on nightly branch: https://github.com/dotnet/dotnet-docker/pull/680

**Pull request closed without merging**
