### PR TITLE
Switch AMD64 sample to composite

### PR DESCRIPTION
**Pull request by richlander**

### CODE REVIEW

**Review by mangod9 — APPROVED** [review]

**Review by mthalman — APPROVED** [review]
This puts amd64 in alignment with the Arm32/64 Dockerfiles.

**Review by mthalman — COMMENTED** [review]
Dockerfiles need to be regenerated.

**Comment by richlander** [comment]
I assume you mean that READMEs. I just regenerated them.

**Review by mthalman — APPROVED** [review]

**Comment by lbussell** [comment]
Do we need to update the Dockerfile suffixes in the test data? https://github.com/dotnet/dotnet-docker/blob/7ce7e75a1699e6fdb6a6e84449c9595dbdd8a6bc/tests/Microsoft.DotNet.Docker.Tests/TestData.cs#L131-L133

@jander-msft

**Comment by jander-msft** [comment]
> Do we need to update the Dockerfile suffixes in the test data?
> 
> https://github.com/dotnet/dotnet-docker/blob/7ce7e75a1699e6fdb6a6e84449c9595dbdd8a6bc/tests/Microsoft.DotNet.Docker.Tests/TestData.cs#L131-L133
> 
> @jander-msft

For consistency sake, yes, I believe that needs to be updated. Though, I don't think it impacts the .NET Monitor tests since they are pulling the sample images rather than building them as part of test runs.

**Comment by lbussell** [comment]
It seems this change isn't applicable anymore. Should we close it @richlander, and re-evaluate later?

**Comment by mangod9** [comment]
why is it not applicable? Was the change done as part of a different PR?

**Comment by lbussell** [comment]
> @mangod9: why is it not applicable?

Due to unforseen circumstances we needed to change the samples to Alpine instead of Ubuntu Chiseled. We could probably still switch the samples to alpine3.18-composite.

**Comment by richlander** [comment]
Ya. Let's close this and update the samples per our updated plans, which include using composite.

**Pull request closed without merging**
