### PR TITLE
Drop caveats about dev cert trust on Linux

### PR DESCRIPTION
**Pull request by amcasey**
As of 9.0 RC1 and 8.0.9, `--trust` should work on Linux as well (though it is only officially supported on Ubuntu and Fedora).

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @richlander

**Comment by richlander** [comment]
What about Alpine? It is very relevant for this repo.

**Comment by amcasey** [comment]
TBH, I expect most linux distros to work, but we've only committed to Ubuntu and Fedora.  If you think Alpine needs to be on the list, we can certainly discuss it.  Are you set up to be able to test that?

Also, to confirm, we're talking about the docker host, not the container OS, right?  You're running docker server and your browser in Alpine?

**Comment by amcasey** [comment]
I made an Alpine VM and HttpClient and curl worked.  I didn't try Edge.

**Comment by richlander** [comment]
Right, container OS.

Alpine is one of the most popular container OSes for us, so it follows that we should support it. It is very much not niche.

**Comment by amcasey** [comment]
The instructions I updated seem to describe commands to be run on the host machine, not on the container.  Am I reading that correctly?

**Review by lbussell — CHANGES_REQUESTED** [review]
Since this does not apply to 8.0.8 and 9.0 Preview 7, please re-target this to the nightly branch.

**Comment by mthalman** [comment]
> Since this does not apply to 8.0.8 and 9.0 Preview 7, please re-target this to the nightly branch.

@lbussell - What's the reasoning for targeting nightly? This is a doc change only which we've historically applied directly to main branch usually.

**Comment by mthalman** [comment]
> > Since this does not apply to 8.0.8 and 9.0 Preview 7, please re-target this to the nightly branch.
> 
> @lbussell - What's the reasoning for targeting nightly? This is a doc change only which we've historically applied directly to main branch usually.

Oh, never mind. I understand now what you're saying about the version.

**Comment by amcasey** [comment]
Back to `main` then?

**Comment by amcasey** [comment]
Also, I'm having some trouble following the instructions and I think I might need some help from a docker expert.  The instructions mount `~/.aspnet/https` from the host machine as `/root/.aspnet/https` in the container, but we've started (as of 8.0?) running as `app` in the container, so it seems like it should actually be mounted as `/home/app/.aspnet/https`.  I made that change locally, but it's still not working because the directory in the container has the same owning uid as the folder in the host OS (i.e. it's not owned by `app`).  The certificate isn't (and shouldn't be) world-readable in the host OS, so it's not accessible to `app` when the app launches in the container.  How can I change the folder owner inside the container?

**Comment by mthalman** [comment]
> Back to `main` then?

No, nightly branch is correct.

**Comment by amcasey** [comment]
Here's an alpine host (dotnet 9.0 RC1) accessing an alpine container (dotnet 8.0.7) using firefox in gnome
image

**Comment by amcasey** [comment]
@lbussell @mthalman Who would I talk to about the mounted volume permissions issues?

**Comment by amcasey** [comment]
Oh, right: https://github.com/dotnet/dotnet-docker/issues/5113

**Comment by amcasey** [comment]
@lbussell If you're going to review user permissions later, I think this PR is ready to go.  Anything else you'd like to revisit?

**Comment by lbussell** [comment]
For context I added this comment: https://github.com/dotnet/dotnet-docker/issues/5113#issuecomment-2284485765.

This PR looks OK to me.

**Review by lbussell — APPROVED** [review]

**Review by mthalman — APPROVED** [review]

**Pull request merged**
