### PR TITLE
Update Aspire Dashboard to Azure Linux 3.0

### PR DESCRIPTION
**Pull request by lbussell**
1/2 of https://github.com/dotnet/dotnet-docker/issues/5375

### CODE REVIEW

**Review by mthalman — APPROVED** [review]

**Review by joperezr — APPROVED** [review]
LGTM

**Comment by richlander** [comment]
I'm wondering if we should have the same policy for the dashboard and monitor images w/rt OS version. It seems we're making a different decision for monitor.

**Comment by lbussell** [comment]
We are going to wait to take this change - I will close this PR once we have some new documentation to link here.

**Comment by lbussell** [comment]
Closing according to our [Azure Linux FedRAMP policy](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-platforms.md#fedramp-compliance).

**Pull request closed without merging**
