### PR TITLE
Update PowerShell to 7.1.0-preview.3

### PR DESCRIPTION
**Pull request by adityapatwardhan**
Update to PowerShell preview based on .NET 5 preview 4

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
Marked as WIP till all testing in completed. About 3 hours.

**Comment by mthalman** [comment]
@adityapatwardhan - Is testing complete yet?

**Comment by adityapatwardhan** [comment]
We have delayed it a bit since the release is moved to next week. Will update in couple of hours.

**Comment by adityapatwardhan** [comment]
@mthalman ready to merge.

**Pull request merged**
