### PR TITLE
Add PowerShell 7.3.0-preview.1 to .NET 7 SDK Dockerfiles

### PR DESCRIPTION
**Pull request by mthalman**
This is currently blocked by https://github.com/dotnet/sdk/pull/22684. We need a newer build of .NET 7 SDK with this fix. Without the fix, it'll cause the following exception when attempting to install the tool:

```
Unhandled exception: System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.<>c.<Execute>b__17_1(NuGetFramework f)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
```

### CODE REVIEW

**Comment by mthalman** [comment]
Blocked by https://github.com/dotnet/arcade/issues/8312

**Comment by MichaelSimons** [comment]
Should this PR get updated to utilize the new install pwsh template - https://github.com/dotnet/dotnet-docker/pull/3382

**Comment by mthalman** [comment]
> Should this PR get updated to utilize the new install pwsh template - #3382

Yes, thanks. I meant to do that. Too many PRs with dependencies on each other.

**Review by MichaelSimons — APPROVED** [review]

**Pull request merged**
