### PR TITLE
Remove package install

### PR DESCRIPTION
**Pull request by richlander**

### CODE REVIEW

**Review by mthalman — COMMENTED** [review]
Doing a search for `clang`, I see that Dockerfile.debian is installing it too. Shouldn't that be using the `aot` SDK image?

**Comment by lbussell** [comment]
> Doing a search for `clang`, I see that Dockerfile.debian is installing it too. Shouldn't that be using the `aot` SDK image?

There aren't any AOT images for Debian.

**Comment by mthalman** [comment]
> > Doing a search for `clang`, I see that Dockerfile.debian is installing it too. Shouldn't that be using the `aot` SDK image?
> 
> There aren't any AOT images for Debian.

Ugh. And yet we show an AOT sample for that distro. 🤔

**Comment by richlander** [comment]
Sure. The Debian sample is to show people what to do if they want to use Debian.

**Review by mthalman — APPROVED** [review]

**Pull request merged**
