### PR TITLE
Refactor Dockerfile directories to align with tags (#1999)

### LINKED ISSUE #1972: Dockerfile directory structure should be refactored.
Currently the Dockerfile directory structure follows the following pattern.

`<.net version>/<repo>/<distro>/<arch>`

This pattern made sense when all of the images were in a single repo within Docker hub - microsoft/dotnet.  The directory structure matched the tag pattern - `<.net version>-<repo>-<distro>-<arch>`.  With the move to MCR, the image variants were split into their own individual repos but the directory structure was not refactored to align with the new tagging pattern  

There is active work to onboard additional image variants.  The first one is [dotnet/monitor](https://github.com/dotnet/dotnet-docker/pull/1950).  The dotnet-monitor tool is going to version independently of the .NET Core product.  Because of this, the top level version number is going to cause confusion because not all repos will have the same version numbers.

The Dockerfile directory structure should be consistent across image variants and should support independent versioning.  Based on this, the following directory structure is recommended:

`<repo>/<product version>/<distro>/<arch>`

### PR DESCRIPTION
**Pull request by MichaelSimons**
Cherry pick of https://github.com/dotnet/dotnet-docker/commit/634bbf538631b1caf15a229159f238341ea2976a from the nightly branch.

Fixes #1972

### CODE REVIEW

**Comment by mthalman** [comment]
I also realized that the filter paths specified in https://github.com/dotnet/dotnet-docker/blob/master/.github/ISSUE_TEMPLATE/releases/net-core-release.md will need to get updated.

**Comment by MichaelSimons** [comment]
* I updated the PR to include the `src` directory (https://github.com/dotnet/dotnet-docker/pull/2009).  
* I also updated the filter paths in https://github.com/dotnet/dotnet-docker/blob/master/.github/ISSUE_TEMPLATE/releases/net-core-release.md.  
* I will back-port the eng/common/build.ps1 changes.
* I will prepare an announcement.

**Comment by houseofcat** [comment]
@MichaelSimons has this been officially released?

I just tried latest Preview 6 SDK and Visual Studio 2019 v16.6.3... still has the wrong directory being created in Visual Studio templates for new apps with Docker support.

Fix is on line 3:
Change `FROM mcr.microsoft.com/dotnet/core/aspnet:5.0-buster-slim AS base`  
To `FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base`

**Comment by MichaelSimons** [comment]
@houseofcat - This PR is unrelated to the problem you are mentioning.  This PR is about re-organizing the Dockerfiles in SCC.  It has nothing to do with the resulting images and which repos/tags they are published to.  The issue you are referring to is related to https://github.com/dotnet/dotnet-docker/issues/1939.  @houseofcat, can you please post your comment to that issue so we can have the discussion in the correct place?

**Comment by houseofcat** [comment]
Absolutely, thanks Michael for helping me with this.

**Pull request merged**
