### PR TITLE
Update Aspire dashboard version to latest preview 5

### PR DESCRIPTION
**Pull request by joperezr**
cc: @lbussell 

FYI: @davidfowl @kvenkatrajan @drewnoakes

### CODE REVIEW

**Review by lbussell — APPROVED** [review]

**Comment by lbussell** [comment]
@joperezr did something with the port change? Looks like the test is failing to hit the endpoint.

**Comment by joperezr** [comment]
cc: @kvenkatrajan @drewnoakes can you help answering @lbussell's question?

**Comment by joperezr** [comment]
I tested the generated image and the issue seems to be related to our new changes for adding Auth to OTLP endpoints. cc @JamesNK, @davidfowl .

This is the output I get when trying to use the image:
```
Unhandled exception. System.InvalidOperationException: Configuration of OTLP endpoint authentication is required. Either specify DOTNET_DASHBOARD_INSECURE_ALLOW_ANONYMOUS with a value of true, or specify DOTNET_DASHBOARD_OTLP_AUTH_MODE. Possible values: None, ApiKey, ClientCertificate
   at Aspire.Dashboard.DashboardWebApplication.LoadDashboardConfig(IConfiguration configuration) in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 403
   at Aspire.Dashboard.DashboardWebApplication..ctor(Action`1 configureBuilder) in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 66
   at Program.<Main>$(String[] args) in /_/src/Aspire.Dashboard/Program.cs:line 7
```

I'm assuming we'd not want to set any of those two and instead just provide docs for users so that they set these variables as appropriate, and for the tests in this repo we should probably just launch the container with the extra env variable for Allow anonymous. Thoughts?

**Comment by lbussell** [comment]
> I'm assuming we'd not want to set any of those two and instead just provide docs for users so that they set these variables as appropriate, and for the tests in this repo we should probably just launch the container with the extra env variable for Allow anonymous. Thoughts?

Thanks for the investigation @joperezr as I've been pretty busy. We can definitely launch the test containers with `DOTNET_DASHBOARD_INSECURE_ALLOW_ANONYMOUS=true`

**Comment by joperezr** [comment]
I pushed a change which will fix the test, but it would be good to check if we also want to change Dockerfile to set some defaults.

**Comment by davidfowl** [comment]
> I pushed a change which will fix the test, but it would be good to check if we also want to change Dockerfile to set some defaults.

Which dockerfile?

**Comment by JamesNK** [comment]
The intent of `DOTNET_DASHBOARD_INSECURE_ALLOW_ANONYMOUS` is for people to make an explicit decision to run without auth. It's not a default.

**Comment by JamesNK** [comment]
btw I think we might rename this setting to `DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS` (insecure -> unsecured).

See https://github.com/dotnet/aspire/pull/3233

**Comment by joperezr** [comment]
> > I pushed a change which will fix the test, but it would be good to check if we also want to change Dockerfile to set some defaults.
> 
> Which dockerfile?

Aspire dashboard [dockerfile](https://github.com/dotnet/dotnet-docker/blob/nightly/src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile). So essentially, before the addition of this check, one could just do `docker run` on the image and it would run the dashboard container. Now, you will get the exception message I pointed out above, unless you either set DOTNET_DASHBOARD_INSECURE_ALLOW_ANONYMOUS to true, or alternatively (and preferably) you set DOTNET_DASHBOARD_OTLP_AUTH_MODE to the appropriate mode. My question is, what do we want the default experience is for someone using our Docker image? Should we expect them to pass one of these environment variables always to their docker run commands (or compose files or whatever), or do we want to provide a default as part of the image which can then later be overriden?

**Comment by JamesNK** [comment]
We want it to be required. Specifying the env var is a user gesture to indicate that they intentionally want to be unsecured.

**Comment by davidfowl** [comment]
Will we show this as the instruction to run in the docs?

**Comment by joperezr** [comment]
> Will we show this as the instruction to run in the docs?

We should, yes. We have a README for our docker image here: https://github.com/dotnet/dotnet-docker/blob/nightly/README.aspire-dashboard.md and there is an open issue tracking filling the content of that before we move to the prod registry: https://github.com/dotnet/dotnet-docker/issues/5153

I've been holding off on filling that README as we still haven't finalized how we expect the interaction of the image should be (meaning we are still adding env vars and config switches) but once we are settled we should fill that in.

**Comment by MichaelSimons** [comment]
> The intent of `DOTNET_DASHBOARD_INSECURE_ALLOW_ANONYMOUS` is for people to make an explicit decision to run without auth. It's not a default.

From a general UX perspective of the Docker aspire image this gives me an allergic reaction.  People are going to pull this image, run it, and not expect an exception.  I can see this as a source of frustration for customers and therefore be source of issues/discussions/questions.  Even if users have to read docs to know how to use the image, I think having the run experience fail is not ideal.

**Comment by joperezr** [comment]
Also, to state the obvious, we don't want users to use `DOTNET_DASHBOARD_INSECURE_ALLOW_ANONYMOUS`, as we instead want them to configure their container with the right parameters such that they run with auth enabled and in a secure manner. The INSECURE env variable should only be set if as a consumer, you understand the risks, and want to proceed anyway, but it is by no means our recommendation. We of course plan to document all of this in the README.

**Comment by MichaelSimons** [comment]
I get all that but I know from experience users are going to pull these images and try running them before reading any documentation.  This was the perspective that prompted my earlier comments.  Having the container do something successful even if the user don't know what to do next is better than throwing an exception IMO.

**Comment by joperezr** [comment]
So given our stance that I described above, what would be your suggestion? Should we change our Dockerfile so that instead of having the entrypoint launch the dashboard to instead launch a script that checks if the required configuration is met, and if not, to print a helpful message? (and of course if it finds the right configs to just launch the app)

**Comment by jander-msft** [comment]
Can the dashboard be changed to run without additional configuration but then display some kind of diagnostic in the shell itself that reports that it hasn't been configured to do anything and provides an fwlink/aka.ms link to docs on how to configure it?

**Comment by joperezr** [comment]
Yes, if you set the environment variable to "opt-in" for insecure mode, the dashboard will run, but since we don't know if people will ready the output and check the note about the fwlink, We'd instead want to make sure that users are explicitly opting-in for this and that it is not a default in the image. This is essentially what @JamesNK said above about: `We want it to be required. Specifying the env var is a user gesture to indicate that they intentionally want to be unsecured.`

**Comment by joperezr** [comment]
This is one of the ones were we want to force the consumer to read the docs 😃

**Comment by mthalman** [comment]
If this is the desired default experience and we want to force the user to read the docs, the error message should probably direct them to the docs with a URL.

**Comment by MichaelSimons** [comment]
> So given our stance that I described above, what would be your suggestion? Should we change our Dockerfile so that instead of having the entrypoint launch the dashboard to instead launch a script that checks if the required configuration is met, and if not, to print a helpful message? (and of course if it finds the right configs to just launch the app)

I lean towards making the exception message as helpful as possible.  e.g. linking to the appropriate documentation.

**Pull request merged**
