### PR TITLE
Tiny format change of Dockerfile.chiseled-composite

### PR DESCRIPTION
**Pull request by simonkurtz-MSFT**
I was looking for the hair in the soup... and I found it.

### CODE REVIEW

**Comment by richlander** [comment]
I assume this is a cosmetic not functional change, correct? Your PR message doesn't clarify that.

**Comment by simonkurtz-MSFT** [comment]
Yes, sorry. It's absolutely, minimally cosmetic only. It caught my eye as I compared Dockerfiles.

**Review by richlander — APPROVED** [review]

**Comment by richlander** [comment]
Thanks!

**Comment by simonkurtz-MSFT** [comment]
[like]  Simon Kurtz reacted to your message:
________________________________

**Pull request merged**
